>  Example13_10  <- read.table ("example13_10.csv", header=TRUE, sep=",")
>  attach(Example13_10)
>  library(gmodels)
>  CrossTable(a, b)
>  mytable  <-  xtabs(~a + b)
>  mcnemar.test(mytable)
>  library(fmsb)
>  Kappa.test(mytable, conf.level=0.95)
>  detach (Example13_10)
