>  Example11_2  <- read.table ("example11_2.csv", header=TRUE, sep=",")
>  attach(Example11_2)
>  Example11_2$han  <- ifelse (x==1, 1, 0)
>  Example11_2$yi   <- ifelse (x==2, 1, 0)
>  Example11_2$hani   <- ifelse (x==3, 1, 0)
>  fit1   <-  glm(y~ han + yi ,  family= binomial(), data=Example11_2)
>  fit2   <-  glm(y~ han + hani,  family= binomial(), data=Example11_2)
>  summary(fit1)
>  coefficients(fit1)
>  exp(coefficients(fit1))
>  exp (confint(fit1))
>  summary(fit2)
>  coefficients(fit2)
>  exp(coefficients(fit2))
>  exp (confint(fit2))
>  detach (Example11_2)
