>  Example11_5  <- read.table ("example11_5.csv", header=TRUE, sep=",")
>  attach(Example11_5)
>  fullfit   <-  glm(y~ x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 ,  family= binomial(), data=Example11_5)
>  summary(fullfit)
>  nothing   <-  glm(y~ 1 ,  family= binomial(), data=Example11_5)
>  summary(nothing)
>  bothways <- step(nothing, list(lower=formula(nothing), upper=formula(fullfit)),  direction="both")
>  fit1   <-  glm(y~ x6 + x5 + x8 + x1 + x2 ,  family= binomial(), data=Example11_5)
>  summary(fit1)
>  fit2   <-  glm(y~ x6 + x5 + x8 + x1 ,  family= binomial(), data=Example11_5)
>  summary(fit2)
>  coefficients(fit2)
>  exp(coefficients(fit2))
>  exp (confint(fit2))
>  detach (Example11_5)
