>  Example8_7  <- read.table ("example8_7.csv", header=TRUE, sep=",")
>  attach(Example8_7)
>  block  <-factor(block, order=FALSE)
>  treat <-factor(treat, order=FALSE)
>  table(block, treat)
>  aggregate(sale, by=list(block), FUN=mean)
>  aggregate(sale, by=list(block), FUN=sd)
>  aggregate(sale, by=list(treat), FUN=mean)
>  aggregate(sale, by=list(treat), FUN=sd)
>  fit <- aov(sale ~ block + treat)
>  summary(fit)
>  TukeyHSD(fit, "block")
>  TukeyHSD(fit, "treat")
>  detach(Example8_7)
