>  install.packages("multcomp")
>  library(multcomp)
>  Example8_1  <- read.table ("example8_1.csv", header=TRUE, sep=",")
>  attach(Example8_1)
>  table(group)
>  aggregate(atp,by=list(group),FUN=mean)
>  aggregate(atp,by=list(group),FUN=sd)
>  fit <- aov(atp~group)
>  summary(fit)

>  install.packages("gplots")
>  library(gplots)
>  plotmeans(atp~group,xlab="group", ylab="ATP", main="Mean Plot\nwith 95% CI")
>  detach (Example8_1)
>  TukeyHSD(fit)
