>  Example8_13  <- read.table ("example8_13.csv", header=TRUE, sep=",")
>  attach(Example8_13)
>  a  <-factor(a, order=FALSE)
>  b  <-factor(b, order=FALSE)
>  s  <-factor(s, order=FALSE)
>  time  <-factor(time, order=FALSE)
>  fit <- aov(y ~a*b*time +Error(s/time))
>  summary(fit)
>  detach(Example8_13)
