>  Example8_14  <- read.table ("example8_14.csv", header=TRUE, sep=",")
>  attach(Example8_14)
>  a  <-factor(a, order=FALSE)
>  b  <-factor(b, order=FALSE)
>  table (a,b)
>  aggregate (y, by=list(b), FUN=mean)
>  aggregate (y, by=list(b), FUN=sd)
>  fit <- aov(y ~x+a+b)
>  summary(fit)
>  detach(Example8_14)
