>  Example8_9  <- read.table ("example8_9.csv", header=TRUE, sep=",")
>  attach(Example8_9)
>  a  <-factor(a, order=FALSE)
>  b  <-factor(b, order=FALSE)
>  table(a, b)
>  aggregate(x, by=list(a), FUN=mean)
>  aggregate(x, by=list(a), FUN=sd)
>  aggregate(x, by=list(b), FUN=mean)
>  aggregate(x, by=list(b), FUN=sd)
>  fit <- aov(x ~ a + b +a:b)
>  summary(fit)
>  TukeyHSD(fit, "a")
>  TukeyHSD(fit, "b")
>  TukeyHSD(fit, "a:b")
>  detach(Example8_9)
