>  Example8_6  <- read.table ("example8_6.csv", header=TRUE, sep=",")
>  attach(Example8_6)
>  block  <-factor(block, order=FALSE)
>  dose  <-factor(dose, order=FALSE)
>  table(block, dose)
>  aggregate(weight, by=list(block), FUN=mean)
>  aggregate(weight, by=list(block), FUN=sd)
>  aggregate(weight, by=list(dose), FUN=mean)
>  aggregate(weight, by=list(dose), FUN=sd)
>  fit <- aov(weight ~ block + dose)
>  summary(fit)
>  TukeyHSD(fit, "dose")
>  TukeyHSD(fit, "block")
>  detach(Example8_6)

