>  Example8_8  <- read.table ("example8_8.csv", header=TRUE, sep=",")
>  attach(Example8_8)
>  site <-factor(c, order=FALSE)
>  rabbnum <-factor(r, order=FALSE)
>  table(site, rabbnum, z)
>  aggregate(x, by=list(site), FUN=mean)
>  aggregate(x, by=list(site), FUN=sd)
>  aggregate(x, by=list(rabbnum), FUN=mean)
>  aggregate(x, by=list(rabbnum), FUN=sd)
>  aggregate(x, by=list(z), FUN=mean)
>  aggregate(x, by=list(z), FUN=sd)
>  fit <- aov(x ~ site + rabbnum + z)
>  summary(fit)
>  TukeyHSD(fit, "site")
>  TukeyHSD(fit, "rabbnum")
>  TukeyHSD(fit, "z")
>  detach(Example8_8)
