> example22_7  <- read.table ("example22_7.csv", header=TRUE, sep=",")
> example22_7
> summary(example22_7)
> attach(example22_7)
> hist(height)
> hist(height, breaks=12, col=¡±red¡± )
> hist(height, breaks=14, col="red", freq=FALSE)
> rug(jitter(height))
> lines(density(height), col="blue", lwd=2)
> h <- hist(height, breaks=14, col="red")
> xfit <-seq(min(height), max(height), length=40)
> yfit <- dnorm(xfit, mean=mean(height), sd=sd(height))
> yfit <- yfit*diff(h$mids[1:2]*length(height))
> lines(xfit, yfit, col="blue", lwd=2)
